# Generated by Django 5.1.3 on 2024-11-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(blank=True, max_length=100, null=True)),
                ('research_genetic', models.CharField(blank=True, max_length=100, null=True)),
                ('research_blood', models.CharField(blank=True, max_length=100, null=True)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='cats/kittens/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OurBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(blank=True, max_length=100, null=True)),
                ('research_genetic', models.CharField(blank=True, max_length=100, null=True)),
                ('research_blood', models.CharField(blank=True, max_length=100, null=True)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='cats/our_boys/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OurGirl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(blank=True, max_length=100, null=True)),
                ('research_genetic', models.CharField(blank=True, max_length=100, null=True)),
                ('research_blood', models.CharField(blank=True, max_length=100, null=True)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='cats/our_girls/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
